const today = new Date();
today.setHours(0, 0, 0, 0);
const yesterday = new Date(today);
yesterday.setDate(today.getDate() - 1);
const dayBeforeYesterday = new Date(today);
dayBeforeYesterday.setDate(today.getDate() - 2);

const formatDateKey = (date: Date) => date.toISOString().split("T")[0];

export const mockDiary = {
  [formatDateKey(today)]: [
    {
      id: 1,
      name: "Apple",
      details: "Apple, 90 g",
      calories: 60,
      extra: [
        { label: "Bread unit", value: 0.5, unit: "gr" },
        { label: "Gram", value: 90, unit: "gr" },
        { label: "Sugar", value: 12, unit: "gr" },
        { label: "Protein", value: 5, unit: "gr" },
        { label: "Fats", value: 0.3, unit: "gr" },
        { label: "Carbs", value: 25, unit: "gr" },
        { label: "Glycemic index", value: 38, unit: "" },
        { label: "Protein-fat units", value: 0.3, unit: "gr" },
        { label: "Insulin", value: 0.1, unit: "gr" },
        { label: "Glucose before", value: "", unit: "mmol/L" },
        { label: "Glucose after", value: "", unit: "mmol/L" },
        { label: "Physical activity", value: "Low", unit: "" },
      ],
    },
    {
      id: 2,
      name: "Avocado",
      details: "Avocado, 55 g",
      calories: 110,
      extra: [
        { label: "Bread unit", value: 0.2, unit: "gr" },
        { label: "Gram", value: 55, unit: "gr" },
        { label: "Sugar", value: 0.2, unit: "gr" },
        { label: "Protein", value: 5, unit: "gr" },
        { label: "Fats", value: 10, unit: "gr" },
        { label: "Carbs", value: 8, unit: "gr" },
        { label: "Glycemic index", value: 15, unit: "" },
        { label: "Protein-fat units", value: 1.5, unit: "gr" },
        { label: "Insulin", value: 0.05, unit: "gr" },
        { label: "Glucose before", value: "", unit: "mmol/L" },
        { label: "Glucose after", value: "", unit: "mmol/L" },
        { label: "Physical activity", value: "Low", unit: "" },
      ],
    },
    {
      id: 3,
      name: "Apple",
      details: "Apple, 90 g",
      calories: 60,
      extra: [
        { label: "Bread unit", value: 0.5, unit: "gr" },
        { label: "Gram", value: 90, unit: "gr" },
        { label: "Sugar", value: 12, unit: "gr" },
        { label: "Protein", value: 5, unit: "gr" },
        { label: "Fats", value: 0.3, unit: "gr" },
        { label: "Carbs", value: 25, unit: "gr" },
        { label: "Glycemic index", value: 38, unit: "" },
        { label: "Protein-fat units", value: 0.3, unit: "gr" },
        { label: "Insulin", value: 0.1, unit: "gr" },
        { label: "Glucose before", value: "", unit: "mmol/L" },
        { label: "Glucose after", value: "", unit: "mmol/L" },
        { label: "Physical activity", value: "Low", unit: "" },
      ],
    },
  ],
  [formatDateKey(yesterday)]: [
    {
      id: 4,
      name: "Banana",
      details: "Banana, 120 g",
      calories: 105,
      extra: [
        { label: "Bread unit", value: 1.0, unit: "gr" },
        { label: "Gram", value: 120, unit: "gr" },
        { label: "Sugar", value: 14, unit: "gr" },
        { label: "Protein", value: 5, unit: "gr" },
        { label: "Fats", value: 0.4, unit: "gr" },
        { label: "Carbs", value: 30, unit: "gr" },
        { label: "Glycemic index", value: 51, unit: "" },
        { label: "Protein-fat units", value: 0.4, unit: "gr" },
        { label: "Insulin", value: 0.12, unit: "gr" },
        { label: "Glucose before", value: "", unit: "mmol/L" },
        { label: "Glucose after", value: "", unit: "mmol/L" },
        { label: "Physical activity", value: "Low", unit: "" },
      ],
    },
    {
      id: 5,
      name: "Egg",
      details: "Egg, 50 g",
      calories: 70,
      extra: [
        { label: "Bread unit", value: 0, unit: "gr" },
        { label: "Gram", value: 50, unit: "gr" },
        { label: "Sugar", value: 0.5, unit: "gr" },
        { label: "Protein", value: 5, unit: "gr" },
        { label: "Fats", value: 5, unit: "gr" },
        { label: "Carbs", value: 1, unit: "gr" },
        { label: "Glycemic index", value: 0, unit: "" },
        { label: "Protein-fat units", value: 6, unit: "gr" },
        { label: "Insulin", value: 0.2, unit: "gr" },
        { label: "Glucose before", value: "", unit: "mmol/L" },
        { label: "Glucose after", value: "", unit: "mmol/L" },
        { label: "Physical activity", value: "Low", unit: "" },
      ],
    },
  ],
  [formatDateKey(dayBeforeYesterday)]: [
    {
      id: 6,
      name: "Chicken Breast",
      details: "Chicken, 150 g",
      calories: 165,
      extra: [
        { label: "Bread unit", value: 0, unit: "gr" },
        { label: "Gram", value: 150, unit: "gr" },
        { label: "Sugar", value: 0, unit: "gr" },
        { label: "Protein", value: 5, unit: "gr" },
        { label: "Fats", value: 3, unit: "gr" },
        { label: "Carbs", value: 0, unit: "gr" },
        { label: "Glycemic index", value: 0, unit: "" },
        { label: "Protein-fat units", value: 31, unit: "gr" },
        { label: "Insulin", value: 0.3, unit: "gr" },
        { label: "Glucose before", value: "", unit: "mmol/L" },
        { label: "Glucose after", value: "", unit: "mmol/L" },
        { label: "Physical activity", value: "Low", unit: "" },
      ],
    },
    {
      id: 7,
      name: "Rice",
      details: "Rice, 100 g",
      calories: 130,
      extra: [
        { label: "Bread unit", value: 1.5, unit: "gr" },
        { label: "Gram", value: 100, unit: "gr" },
        { label: "Sugar", value: 0.1, unit: "gr" },
        { label: "Protein", value: 5, unit: "gr" },
        { label: "Fats", value: 0.2, unit: "gr" },
        { label: "Carbs", value: 28, unit: "gr" },
        { label: "Glycemic index", value: 70, unit: "" },
        { label: "Protein-fat units", value: 2.7, unit: "gr" },
        { label: "Insulin", value: 0.15, unit: "gr" },
        { label: "Glucose before", value: "", unit: "mmol/L" },
        { label: "Glucose after", value: "", unit: "mmol/L" },
        { label: "Physical activity", value: "Low", unit: "" },
      ],
    },
    {
      id: 8,
      name: "Broccoli",
      details: "Broccoli, 80 g",
      calories: 28,
      extra: [
        { label: "Bread unit", value: 0.3, unit: "gr" },
        { label: "Gram", value: 80, unit: "gr" },
        { label: "Sugar", value: 1.7, unit: "gr" },
        { label: "Protein", value: 5, unit: "gr" },
        { label: "Fats", value: 0.1, unit: "gr" },
        { label: "Carbs", value: 7, unit: "gr" },
        { label: "Glycemic index", value: 10, unit: "" },
        { label: "Protein-fat units", value: 2.8, unit: "gr" },
        { label: "Insulin", value: 0.05, unit: "gr" },
        { label: "Glucose before", value: "", unit: "mmol/L" },
        { label: "Glucose after", value: "", unit: "mmol/L" },
        { label: "Physical activity", value: "Low", unit: "" },
      ],
    },
  ],
};